Update package exports and peer dependencies
tabler/tabler-icons pull request #116
Opened 2021-02-24 08:38 UTC by adambrgmn

This PR updates the main et.al. fields to point to the correct dist files as discussed in #113. It also updates the react peer dependencies to be a bit looser than before, as discussed in #115.

Hope you don't mind that I took the liberty of providing this PR, I know managing a popular OSS library can be cumbersome. I would like you to know that I really appreciate the work and love the quality of the icons!

2021-03-10 14:13 UTC, aulneau commented
Came here to make this same PR. @codecalm anyway you can give this your 👀  and merge it in? Would prefer to not have to fork and publish a different pkg just for these changes.

2021-03-10 15:42 UTC, aulneau requested changes

2021-03-10 15:42 UTC, aulneau commented on package.json
> -  "browser": "./icons-react/dist/index.umd.js",
This breaks the build, fyi. the rollup config depends on the browser field. `pkg['umd:main']` fixes it.

2021-03-10 19:59 UTC, adambrgmn commented on package.json
> -  "browser": "./icons-react/dist/index.umd.js",
Oh, thanks! I thought I had verified that, but realized I switched from `umd:main` to `browser` just before making the PR. Can't remember why 🤷‍♂️ I'll fix it.

2021-04-09 16:50 UTC, FreexD approved these changes
LGTM! Thank you for the great work :)

2021-04-09 20:51 UTC, Benjozork commented
Thanks for the PR! Our projects depends on Tabler a lot and this was a pain point since we use React 17.0 across the board.

2021-04-10 14:14 UTC, merged

2021-04-11 07:43 UTC, theMasix commented
Any package release due to this PR? @FreexD

2021-04-11 10:12 UTC, FreexD commented
@theMasix it will be released this week with a bunch of new icons in `v1.40` :)